Apply all migrations: admin, auth, contenttypes, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers
Traceback (most recent call last):
  File "C:\Users\dhyey\OneDrive\Desktop\Project\company\APHELION CYBER SITE TEST 2\manage.py", line 20, in <module>
    main()
  File "C:\Users\dhyey\OneDrive\Desktop\Project\company\APHELION CYBER SITE TEST 2\manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\core\management\base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\core\management\commands\migrate.py", line 299, in handle
    pre_migrate_apps = pre_migrate_state.apps
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\utils\functional.py", line 47, in __get__
instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\db\migrations\state.py", line 589, in apps  
    return StateApps(self.real_apps, self.models)  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\db\migrations\state.py", line 650, in __init__
    self.render_multiple([*models.values(), *self.real_models])
  File "C:\Users\dhyey\anaconda3\Lib\site-packages\django\db\migrations\state.py", line 692, in render_multiple
    raise InvalidBasesError(
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'blog.BlogIndexPage'>, <ModelState: 'blog.BlogPage'>, <ModelState: 'blog.WebinarIndexPage'>, <ModelState: 'blog.WebinarPage'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/5.2/topics/migrations/#dependencies for more